"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Persona_1 = require("./Persona");
var Cuenta_1 = require("./Cuenta");
var pepe = new Persona_1.Persona('pepe', 123456);
var pepeAcount = new Cuenta_1.cuenta(pepe);
var juan = new Persona_1.Persona('juan', 654321);
var juanAcount = new Cuenta_1.cuenta(juan, 15026);
pepeAcount.mostrarCuenta();
pepeAcount.ingresarMonto(10);
pepeAcount.mostrarCuenta();
pepeAcount.retirarMonto(50);
pepeAcount.mostrarCuenta();
console.log();
juanAcount.mostrarCuenta();
juanAcount.ingresarMonto(10);
juanAcount.mostrarCuenta();
juanAcount.retirarMonto(50);
juanAcount.mostrarCuenta();
