"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Perro_1 = require("./Perro");
var Gato_1 = require("./Gato");
var Pajaro_1 = require("./Pajaro");
var oddie = new Perro_1.Perro('Scooby doo', 15, 'Gran Danes', 'Grande');
var garfield = new Gato_1.Gato('garfield', 5, 'naranja', 'amarillo');
var loco = new Pajaro_1.Pajaro('Twetty', 1, 'Canario', 'duro');
oddie.buscarObjeto('Enemigos');
oddie.hacer_sonido();
oddie.moverse();
garfield.moverse();
garfield.hacer_sonido();
garfield.Jugar('oddie');
loco.moverse();
loco.hacer_sonido();
loco.volar();
console.log(loco.getTipo_de_pico());
console.log('///////////////////');
console.log(oddie);
console.log('///////////////////');
console.log(garfield);
console.log('///////////////////');
console.log(loco);
