"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var auto_1 = require("./auto");
var registroAutomotor_1 = require("./registroAutomotor");
var registro = new registroAutomotor_1.RegistroAutomotor;
var auto1 = new auto_1.Auto("Ford", "Lucas", "Aa654SC");
var auto2 = new auto_1.Auto("Ferrari", "Franco", "Aa654SB");
var auto3 = new auto_1.Auto("Ford", "Kevin", "AC789SC");
var auto4 = new auto_1.Auto("Lamborghini", "Ayelen", "Aj654SC");
var auto5 = new auto_1.Auto("Buggati", "Mario", "Aa654SC");
registro.agregarAuto(auto1);
registro.agregarAuto(auto2);
registro.agregarAuto(auto3);
registro.agregarAuto(auto4);
registro.agregarAuto(auto5);
console.log("------------------------");
registro.imprimirRegistro();
console.log("--------------------------");
registro.eliminarAuto("Aa654SC");
console.log("--------------------------");
registro.transferirAuto("Franco");
console.log("--------------------------");
registro.consultasPatente("Aa654SB");
console.log("--------------------------");
registro.consultasPatente("Aa654iB");
console.log("--------------------------");
registro.imprimirRegistro();
